sudo: true
language: rust
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.rustup
before_cache:
  - rm -rf /home/travis/.cargo/registry
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
