name: rust-starter 
args:
    - verbose:
        short: v
        multiple: true
        help: Set the level of verbosity
    - config:
        short: c
        long: config 
        value_name: FILE 
        help: Set a custom config file.
        takes_value: true
subcommands: 
    - hazard:
        about: Generate a hazardous occurance
    - config:
        about: Display the config file contents.
