name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: export package_name=$(sed -En 's/name[[:space:]]*=[[:space:]]*"([^"]+)"/\1/p' Cargo.toml | head -1)
    - run: echo $(sed -En 's/name[[:space:]]*=[[:space:]]*"([^"]+)"/\1/p' Cargo.toml | head -1)
    - run: export package_version=$(sed -En 's/version[[:space:]]*=[[:space:]]*"([^"]+)"/\1/p' Cargo.toml | head -1)
    - run: export dockerhub_org=ruststarter
    - run: mv docker/.dockerignore .dockerignore
    - name: Build the Docker image
      run: docker build --tag rust-starter:0.0.1 --file docker/Dockerfile .
    - run: docker images
    - run: docker push ruststarter/rust-starter:0.0.1
